### ISSUE TITLE
[CI] Fix Github Action

### ISSUE THREAD

**Issue by siriscmv** [CSC-510-G55/PopcornPicks#21]
Currently, all GitHub actions on the forked repo seem to fail with similar error messages. Investigate and fix.

**Comment by balaji305** [comment]
All the actions are fixed. Code Coverage badge is also fixed. 

- [PR - Black](https://github.com/CSC-510-G55/PopcornPicks/commit/d468b5ea6ac6365bc60a5f111f0009ca315c5460)
- [PR - UnitTest](https://github.com/CSC-510-G55/PopcornPicks/commit/912ab24147ab944052a9d6c45646df18c26a6ffb)
- [PR - Mail Credentials](https://github.com/CSC-510-G55/PopcornPicks/commit/9f9e5650c2cdaec5cc6c1f026348f923ccdf57db)
- [PR - Code Coverage](https://github.com/CSC-510-G55/PopcornPicks/commit/0d64e4e770508d5fa34c777b7bc44a3a2450976d)
